#!/usr/zsh

ln -sf ~/config/tmux.conf ~/.tmux.conf
ln -sf ~/private_config/zshrc ~/.zshrc
ln -sf ~/config/fish ~/.config/fish
ln -sf ~/config/starship.toml ~/.config/starship.toml
ln -sf ~/config/nvim ~/.config/nvim
