#!/usr/bin/env zsh

# NeoVim setup - src: ThePrimeagen
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/custom
mkdir -p ~/.config/nvim/lua/custom/efm
mkdir -p ~/.config/nvim/ftplugin

# link wholesale
# @note this probably only works on MacOS - it seems like there are some differences in find between MacOS and Linux
for f in `find -E . -regex ".*\.(vim|lua|yaml)$"`; do
  rm -rf ~/.config/nvim/$f
  ln -s ~/config/$f ~/.config/nvim/$f
done

# Other setup

rm ~/.tmux.conf
rm ~/.zshrc
ln -s ~/config/tmux.conf ~/.tmux.conf
ln -s ~/config/zshrc ~/.zshrc
