set number
set relativenumber
set colorcolumn=120
set tabstop=2
set shiftwidth=2
set expandtab
set nowrap
set splitright
set splitbelow
set smartindent
set shiftround
set noerrorbells
set signcolumn=yes
set cursorline
set hidden
set showtabline=1
set switchbuf=usetab
